Fix to Issue #13
https://foss.heptapod.net/zilf/zlr/-/issues/13

Anchorhead (anchor.z8) throws this exception:
```
System.AggregateException: One or more errors occurred. (Opcode VAR:233 at $2c8f5)
 ---> System.NotImplementedException: Opcode VAR:233 at $2c8f5
   at ZLR.VM.ZMachine.DecodeOneOp(OperandType[] operandTypes, Int16[] argv)
   at ZLR.VM.ZMachine.CompileZCode()
   at ZLR.VM.ZMachine.JitLoopAsync()
   at ZLR.VM.ZMachine.RunAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ZLR.Interfaces.SystemConsole.Program.Main(String[] args)
Press any key to exit...
 ```
That's because there is no call sign defined for `PULL/POP` for version 7 or 8.

Changing the lines 165-166 in `ZLR.VM..Opcodes_VAR` from
```
        [Opcode(OpCount.Var, 233, IndirectVar = true, MaxVersion = 5)]
        [Opcode(OpCount.Var, 233, Store = true, MinVersion = 6, MaxVersion = 6)]
```
to
```
        [Opcode(OpCount.Var, 233, IndirectVar = true, MaxVersion = 5)]
        [Opcode(OpCount.Var, 233, Store = true, MinVersion = 6, MaxVersion = 6)]
        [Opcode(OpCount.Var, 233, IndirectVar = true, MinVersion = 7, MaxVersion = 8)]
```
Fixes this bug.